### ISSUE TITLE
Add Clustering Model to AutoLearn from PyCaret

### ISSUE THREAD

**Issue by espin086** [espin086/AutoLearn#4]
Just like you did with classification, but add now a clustering algorithm, you can find info here: https://towardsdatascience.com/introduction-to-clustering-in-python-with-pycaret-5d869b9714a3

I am not sure if PyCaret we need it to run a bunch of clustering algorithms and display statistics as well

**Comment by ZaibyS** [comment]
@espin086 
Today, I did R&D to integrate a clustering model. So we can have the following approach that we view all available models, select specific ones from the list, and subsequently apply clustering algorithms to the data. Then analyze the resulting statistics, including Silhouette, Calinski-Harabasz, Davies-Bouldin, etc., for each model. And then identify and choose the most effective model based on these metrics. This chosen model can be then utilized for clustering the data and assigning labels accordingly. The reason is that in Pycaret we do not have compare_model functionality in clustering which compares the metrics and chooses the best models as we have in classification and regression and we have to choose the model manually. Alternatively, we can opt for another approach by utilizing a single fixed model, such as k-means, across all datasets or problems and have the elbow method to determine the optimal number of clusters for that dataset. Subsequently, we can cluster the dataset using k-means with the identified best number of clusters.

**Comment by ZaibyS** [comment]
@espin086 
Which approach should we proceed with, and which one seems more suitable to you?

**Comment by espin086** [comment]
@ZaibyS - let’s keep it simple for now and please do this: 

1. Run a bunch of different clustering models
2. Display their metrics like we do for the regression and classification
3. Only select the best model so it can be downloaded, this way it matches how we select and download the best model. To select the best model use the Silhouette score and pick the one with the best siloutte

**Comment by ZaibyS** [comment]
@espin086 
Done with the implementation of the clustering model and all the different clustering models execute, displaying their metrics. The model with the highest silhouette score is chosen as the best model and have also conducted testing on various clustering datasets.
